using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HelperUnionsGenerator;

/// <summary>
/// Generates HelperUnions source code for union declarations.
/// </summary>
[Generator]
public sealed class UnionSourceGenerator : IIncrementalGenerator
{
    private const string UnionAttributeFullyQualifiedName = "HelperUnions.UnionAttribute";

    /// <summary>
    /// Initializes the source generator pipeline.
    /// </summary>
    /// <param name="context">Generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var unionRecords = context.SyntaxProvider
            .CreateSyntaxProvider(static (node, _) => node is RecordDeclarationSyntax { AttributeLists.Count: > 0 },
                static (syntaxContext, _) => GetUnionCandidate(syntaxContext))
            .Where(static candidate => candidate is not null)
            .Select(static (candidate, _) => candidate!);

        context.RegisterSourceOutput(unionRecords, static (productionContext, candidate) =>
        {
            if (!candidate.HasVariants)
            {
                return;
            }

            var source = GenerateAbstractBase(candidate);
            productionContext.AddSource($"{candidate.HintName}.UnionBase.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static UnionCandidate? GetUnionCandidate(GeneratorSyntaxContext syntaxContext)
    {
        if (syntaxContext.Node is not RecordDeclarationSyntax recordDeclaration)
        {
            return null;
        }

        if (syntaxContext.SemanticModel.GetDeclaredSymbol(recordDeclaration) is not INamedTypeSymbol unionSymbol)
        {
            return null;
        }

        if (!HasUnionAttribute(unionSymbol) || !IsPartial(recordDeclaration))
        {
            return null;
        }

        var hasVariants = unionSymbol
            .GetTypeMembers()
            .Any(typeMember =>
                typeMember.IsRecord &&
                typeMember.IsSealed &&
                SymbolEqualityComparer.Default.Equals(typeMember.BaseType, unionSymbol));

        return new UnionCandidate(
            unionSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : unionSymbol.ContainingNamespace.ToDisplayString(),
            GetContainingTypeChain(unionSymbol),
            BuildRecordDeclaration(unionSymbol),
            unionSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat).Replace('<', '_').Replace('>', '_'),
            hasVariants);
    }

    private static bool HasUnionAttribute(INamedTypeSymbol unionSymbol)
    {
        return unionSymbol
            .GetAttributes()
            .Any(attribute =>
                attribute.AttributeClass?.ToDisplayString() == UnionAttributeFullyQualifiedName);
    }

    private static bool IsPartial(RecordDeclarationSyntax recordDeclaration)
    {
        return recordDeclaration.Modifiers.Any(static modifier => modifier.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword));
    }

    private static string GenerateAbstractBase(UnionCandidate candidate)
    {
        var sourceBuilder = new StringBuilder();

        sourceBuilder.AppendLine("// <auto-generated />");
        sourceBuilder.AppendLine("#nullable enable");
        sourceBuilder.AppendLine();

        if (candidate.Namespace is not null)
        {
            sourceBuilder.AppendLine($"namespace {candidate.Namespace};");
            sourceBuilder.AppendLine();
        }

        foreach (var containingType in candidate.ContainingTypeChain)
        {
            sourceBuilder.AppendLine($"{containingType}");
            sourceBuilder.AppendLine("{");
        }

        sourceBuilder.AppendLine($"{candidate.Declaration}");
        sourceBuilder.AppendLine("{");
        sourceBuilder.AppendLine("    private " + ExtractRecordName(candidate.Declaration) + "() { }");
        sourceBuilder.AppendLine("}");

        for (var i = candidate.ContainingTypeChain.Count - 1; i >= 0; i--)
        {
            sourceBuilder.AppendLine("}");
        }

        return sourceBuilder.ToString();
    }

    private static string BuildRecordDeclaration(INamedTypeSymbol unionSymbol)
    {
        var accessibility = unionSymbol.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal"
        };

        var typeParameters = unionSymbol.TypeParameters.Length == 0
            ? string.Empty
            : $"<{string.Join(", ", unionSymbol.TypeParameters.Select(typeParameter => typeParameter.Name))}>";

        return $"{accessibility} abstract partial record {unionSymbol.Name}{typeParameters}";
    }

    private static List<string> GetContainingTypeChain(INamedTypeSymbol symbol)
    {
        var chain = new List<string>();
        var current = symbol.ContainingType;

        while (current is not null)
        {
            chain.Insert(0, BuildContainingTypeDeclaration(current));
            current = current.ContainingType;
        }

        return chain;
    }

    private static string BuildContainingTypeDeclaration(INamedTypeSymbol containingType)
    {
        var accessibility = containingType.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal"
        };

        var kind = containingType.TypeKind == TypeKind.Struct ? "struct" : "class";
        var typeParameters = containingType.TypeParameters.Length == 0
            ? string.Empty
            : $"<{string.Join(", ", containingType.TypeParameters.Select(typeParameter => typeParameter.Name))}>";

        return $"{accessibility} partial {kind} {containingType.Name}{typeParameters}";
    }

    private static string ExtractRecordName(string declaration)
    {
        const string marker = " record ";
        var markerIndex = declaration.IndexOf(marker, StringComparison.Ordinal);
        var nameStartIndex = markerIndex + marker.Length;
        var genericStartIndex = declaration.IndexOf('<', nameStartIndex);

        return genericStartIndex >= 0
            ? declaration.Substring(nameStartIndex, genericStartIndex - nameStartIndex)
            : declaration.Substring(nameStartIndex);
    }

    private sealed class UnionCandidate
    {
        public UnionCandidate(
            string? @namespace,
            IReadOnlyList<string> containingTypeChain,
            string declaration,
            string hintName,
            bool hasVariants)
        {
            Namespace = @namespace;
            ContainingTypeChain = containingTypeChain;
            Declaration = declaration;
            HintName = hintName;
            HasVariants = hasVariants;
        }

        public string? Namespace { get; }

        public IReadOnlyList<string> ContainingTypeChain { get; }

        public string Declaration { get; }

        public string HintName { get; }

        public bool HasVariants { get; }
    }
}
