import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  architectureSidebar: [
    'overview',
    {
      type: 'category',
      label: 'By Project',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'by-project/helper-monads',
          label: 'HelperMonads',
        },
        {
          type: 'doc',
          id: 'by-project/business-rules',
          label: 'BusinessRules',
        },
      ],
    },
    {
      type: 'category',
      label: 'Decisions (ADRs)',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'decisions'}],
    },
    {
      type: 'category',
      label: 'Design',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'design'}],
    },
  ],
};

export default sidebars;
